quarkus.http.port=${HTTP_PORT:8082}

quarkus.http.test-port=8092


quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:mongodb://localhost:27017}
%prod.quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:mongodb://mongodb:27017}
quarkus.mongodb.database=${MONGODB_DATABASE:eshop_users}
app.seed-products=${APP_SEED_PRODUCTS:true}

%test.quarkus.mongodb.database=eshop_users_test
%test.app.seed-products=false

mp.jwt.verify.publickey.location=${JWT_VERIFY_KEY_LOCATION:keys/publicKey.pem}
mp.jwt.verify.issuer=${JWT_ISSUER:grocery-eshop}

smallrye.jwt.sign.key.location=${JWT_SIGN_KEY_LOCATION:keys/privateKey.pem}
smallrye.jwt.new-token.issuer=${JWT_ISSUER:grocery-eshop}
smallrye.jwt.new-token.lifespan=${JWT_TOKEN_LIFESPAN:3600}

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS

