server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Static frontend files
    location / {
        try_files $uri $uri/ =404;
    }

    # user-service
    location /auth/ {
        proxy_pass http://user-service:8080/auth/;
        proxy_set_header Host $host;
    }

    location /users/ {
        proxy_pass http://user-service:8080/users/;
        proxy_set_header Host $host;
    }

    # catalog-service
    location /products {
        proxy_pass http://catalog-service:8080/products;
        proxy_set_header Host $host;
    }

    # order-service
    location /cart {
        proxy_pass http://order-service:8080/cart;
        proxy_set_header Host $host;
    }

    location /checkout {
        proxy_pass http://order-service:8080/checkout;
        proxy_set_header Host $host;
    }

    location /orders {
        proxy_pass http://order-service:8080/orders;
        proxy_set_header Host $host;
    }
}