quarkus.http.port=${HTTP_PORT:8081}

quarkus.http.test-port=8091

quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:mongodb://localhost:27017}
quarkus.mongodb.database=${MONGODB_DATABASE:eshop-catalog}
app.seed-products=${APP_SEED_PRODUCTS:true}

%test.quarkus.mongodb.database=eshop-catalog-test
%test.app.seed-products=false
