%dev.quarkus.mongodb.connection-string=mongodb://localhost:27017
%dev.quarkus.mongodb.database=grocery-shop
%dev.app.seed-products=true

%test.quarkus.mongodb.database=grocery-shop-test
%test.app.seed-products=false
