quarkus.http.port=${HTTP_PORT:8083}

quarkus.http.test-port=8093

quarkus.rest-client.catalog-api.url=${CATALOG_API_URL:http://localhost:8081}
%prod.quarkus.rest-client.catalog-api.url=${CATALOG_API_URL:http://catalog-service:8080}

quarkus.rest-client.user-api.url=${USER_API_URL:http://localhost:8082}
%prod.quarkus.rest-client.user-api.url=${USER_API_URL:http://user-service:8080}

quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:mongodb://localhost:27017}
%prod.quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:mongodb://mongodb:27017}
quarkus.mongodb.database=${MONGODB_DATABASE:eshop_orders}

%test.quarkus.mongodb.database=eshop_orders_test

mp.jwt.verify.publickey.location=${JWT_VERIFY_KEY_LOCATION:keys/publicKey.pem}
mp.jwt.verify.issuer=${JWT_ISSUER:grocery-eshop}

%test.smallrye.jwt.sign.key.location=keys/privateKey.pem
%test.smallrye.jwt.new-token.issuer=grocery-eshop
%test.smallrye.jwt.new-token.lifespan=3600

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS

